name: crucible-merged

on:
  pull_request_target:
    types: [ closed ]
    branches: [ master ]
    paths-ignore:
    - LICENSE
    - '**.md'
    - '.github/rulesets/**'
    - .github/workflows/run-crucible-tracking.yaml
    - .github/workflows/crucible-scheduled.yaml
    - .github/workflows/crucible-weekly-ci.yaml
    - .github/workflows/crucible-release-ci.yaml
    - .github/workflows/faux-crucible-release-ci.yaml
    - .github/workflows/faux-crucible-ci.yaml
    - .github/workflows/faux-ci.yaml
    - .github/workflows/crucible-release.yaml
    - 'docs/**'
    - 'spec/**'
  workflow_dispatch:

jobs:
  call-core-crucible-ci_if-merged:
    if: github.event.pull_request.merged == true
    uses: perftool-incubator/crucible-ci/.github/workflows/core-release-crucible-ci.yaml@main
    with:
      ci_target: "crucible"
      ci_target_branch: "master"
      github_workspace: "$GITHUB_WORKSPACE"
      bypass_controller_build: "yes"
    secrets:
      production_registry_auth: ${{ secrets.CRUCIBLE_PRODUCTION_ENGINES_REGISTRY_AUTH }}
      quay_oauth_token: ${{ secrets.CRUCIBLE_QUAYIO_OAUTH_TOKEN }}
