name: crucible-release-ci

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
    - LICENSE
    - '**.md'
    - '.github/rulesets/**'
    - .github/workflows/run-crucible-tracking.yaml
    - .github/workflows/crucible-merged.yaml
    - .github/workflows/crucible-weekly-ci.yaml
    - .github/workflows/crucible-scheduled.yaml
    - .github/workflows/faux-crucible-release-ci.yaml
    - .github/workflows/faux-crucible-ci.yaml
    - .github/workflows/faux-ci.yaml
    - 'docs/**'
    - 'spec/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}/release-ci
  cancel-in-progress: true

jobs:
  call-crucible-release-remove:
    uses: ./.github/workflows/crucible-release.yaml
    with:
      custom_release: "ci-version-test"
      action: "delete"
      force_create: true
    secrets:
      PRIVATE_KEY__TAG_CRUCIBLE_RELEASE: ${{ secrets.PRIVATE_KEY__TAG_CRUCIBLE_RELEASE }}

  call-crucible-release-create:
    uses: ./.github/workflows/crucible-release.yaml
    needs: call-crucible-release-remove
    with:
      custom_release: "ci-version-test"
      action: "create"
    secrets:
      PRIVATE_KEY__TAG_CRUCIBLE_RELEASE: ${{ secrets.PRIVATE_KEY__TAG_CRUCIBLE_RELEASE }}

  call-crucible-release-update:
    uses: ./.github/workflows/crucible-release.yaml
    needs: call-crucible-release-create
    with:
      custom_release: "ci-version-test"
      action: "update"
    secrets:
      PRIVATE_KEY__TAG_CRUCIBLE_RELEASE: ${{ secrets.PRIVATE_KEY__TAG_CRUCIBLE_RELEASE }}

  crucible-release-ci-complete:
    runs-on: [ self-hosted, workflow-overhead ]
    timeout-minutes: 10
    needs: call-crucible-release-update
    steps:
    - name: complete
      run: echo "crucible-release-ci-complete"
