name: crucible-ci

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
    - LICENSE
    - '**.md'
    - '.github/rulesets/**'
    - .github/workflows/run-crucible-tracking.yaml
    - .github/workflows/crucible-merged.yaml
    - .github/workflows/crucible-scheduled.yaml
    - .github/workflows/crucible-weekly-ci.yaml
    - .github/workflows/crucible-release-ci.yaml
    - .github/workflows/faux-crucible-release-ci.yaml
    - .github/workflows/faux-crucible-ci.yaml
    - .github/workflows/faux-ci.yaml
    - .github/workflows/crucible-release.yaml
    - 'docs/**'
    - 'spec/**'
  workflow_dispatch:

jobs:
  call-core-release-crucible-ci:
    uses: perftool-incubator/crucible-ci/.github/workflows/core-release-crucible-ci.yaml@main
    with:
      ci_target: "crucible"
      ci_target_branch: "${{ github.ref }}"
      github_workspace: "$GITHUB_WORKSPACE"
    secrets:
      ci_registry_auth: ${{ secrets.CRUCIBLE_CI_ENGINES_REGISTRY_AUTH }}
      quay_oauth_token: ${{ secrets.CRUCIBLE_QUAYIO_OAUTH_TOKEN }}
