name: faux-crucible-release-ci

on:
  pull_request:
    branches: [ master ]
    paths:
    - LICENSE
    - '**.md'
    - '.github/rulesets/**'
    - .github/workflows/run-crucible-tracking.yaml
    - .github/workflows/crucible-merged.yaml
    - .github/workflows/crucible-weekly-ci.yaml
    - .github/workflows/crucible-scheduled.yaml
    - .github/workflows/faux-crucible-release-ci.yaml
    - .github/workflows/faux-crucible-ci.yaml
    - .github/workflows/faux-ci.yaml
    - 'docs/**'
    - 'spec/**'

jobs:
  crucible-release-ci-complete:
    runs-on: [ self-hosted, workflow-overhead ]
    steps:
    - run: echo "faux-crucible-release-ci-complete"
